apiVersion: v1
kind: Pod
metadata:
  name: dbpod
spec:
  containers:
    - name: dbcontainer
      image: mariadb:latest
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: dbconfig
